export const COVER_LIST_INIT = '[COVER] COVER_LIST_INIT';
export const COVER_LIST_SUCCESS = '[COVER] COVER_LIST_SUCCESS';
export const COVER_LIST_ERROR = '[COVER] COVER_LIST_ERROR';
export const COVER_ACTIVE_PLAY = '[COVER] COVER_ACTIVE_PLAY';
export const COVER_SELECTED_TRACK = '[COVER] COVER_SELECTED_TRACK';
